### ISSUE TITLE
Add another mitigation? Only display QR Codes in an authenticated session on the original device

### ISSUE THREAD

**Issue by damienbod** [oauthstuff/draft-cross-device-security#9]
## Use Case

I want to use my E-ID on a verifier website to prove my identity. If I authenticated on the correct website using a phishing resistant authentication and only after this, can I scan the QR Code to present my verifiable credentials presentation. This works good, as a lot of the website where I require a digital identity check, I already have an account and can use a phishing resistant authentication first.

I could add a text for this, if you think this is a good idea.

Greetings Damien

**Comment by PieterKas** [comment]
@damienbod I think of this as a type of "authenticated flow" where the user authenticated the channel before engaging in an additional cross device flow. I think it is a reasonable mitigation, would you like to take a stab at writing up a more detailed description of the attack?

**Comment by damienbod** [comment]
@PieterKas Thanks for the feedback. I created a PR for this:

https://github.com/oauthstuff/draft-cross-device-security/pull/19

Greetings Damien
